defaults:
  - decoder: unet3plus_decoder
  - encoder: unet3plus_encoder
  - loss: mse
  - optimizer: adam
  - scheduler: plateau

_target_: dlwp.model.models.CubeSphereUnet
_recursive_: false
input_time_dim: ${data.input_time_dim}
output_time_dim: ${data.output_time_dim}
cube_dim: ${data.cube_dim}
batch_size: ${batch_size}

# Parameters automatically overridden in train code
# input_channels
# output_channels
# n_constants
# decoder_input_channels
input_channels: 6
output_channels: 6
n_constants: 2
decoder_input_channels: 1