_target_: training.dlwp.model.models.unet.UnetEncoder
_recursive_: false
n_channels:
  - 64
  - 128
  - 256
convolutions_per_depth: 2
kernel_size: 3
pooling_type: torch.nn.MaxPool2d
pooling: 2
activation:
  _target_: training.dlwp.model.layers.activations.CappedLeakyReLU
  cap_value: 10.
add_polar_layer: true
flip_north_pole: true